spring:
  application:
    name: provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.17.134:8848

server:
  port: 9000

management:
  endpoints:
    web:
      exposure:
        include: "*"