spring:
  application:
    name: business-service
  cloud:
      nacos:
        discovery:
          server-addr: 192.168.17.134:8848
server:
  port: 9001

  ##Feign 是自带熔断器的，但默认是关闭的。需要在配置文件中配置打开它
feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"